{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "discord-dnd-bot.serviceAccountName" . }}
  labels:
    {{- include "discord-dnd-bot.labels" . | nindent 4 }}
  {{- $annotations := .Values.serviceAccount.annotations | default dict }}
  {{- if and .Values.s3.enabled .Values.s3.iam.enabled }}
  {{- $annotations = merge (dict "eks.amazonaws.com/role-arn" (include "discord-dnd-bot.s3RoleArn" .)) $annotations }}
  {{- end }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
